fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    mysql: "git://github.com/puppetlabs/puppetlabs-mysql.git"
    drbd: "git://github.com/hunner/puppetlabs-drbd.git"
    corosync: "git://github.com/hunner/puppetlabs-corosync.git"
    concat: "git://github.com/ripienaar/puppet-concat.git"
  symlinks:
    ha: "#{source_dir}"
